on:
  schedule:
    - cron: "5 * * * *"

name: fetch-data-wfs

jobs:
  fetch-data-from-wfs:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          ref: read-wfs

      - name: setup R
        uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - name: setup pandoc
        uses: r-lib/actions/setup-pandoc@master

      - name: Read data from WFS
        run: |
          source("src/read_data_from_wfs.R")
        shell: Rscript {0}

      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          commit_prefix: "[AUTO]"
          commit_message: "Fetch data"

      - name: Checkout repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
